# -*- coding: utf-8
from __future__ import unicode_literals

from optparse import OptionParser, OptionError
from .option import CommandOption

COMMAND_NAMES = [
    'build',
    'clear',
    'exec',
    'help',
    'images',
    'info',
    'inspect',
    'logs',
    'ps',
    'pull',
    'pause',
    'port',
    'run',
    'rm',
    'rmi',
    'search',
    'shell',
    'start',
    'stop',
    'top',
    'unpause',
    'version',
]


OPTION_HELP = CommandOption(
    CommandOption.TYPE_BOOLEAN, '-h', '--help',
    action='store_true',
    dest='help',
    help='Display help for this command.')


COMMAND_OPTIONS = {
    'build': [
        CommandOption(CommandOption.TYPE_IMAGE, '-t', '--tag',
                      dest='tag',
                      help=('Repository name (and optionally a tag) to be '
                            'applied to the resulting image in case of '
                            'success.')),
        CommandOption(CommandOption.TYPE_BOOLEAN, '-q', '--quiet',
                      action='store_true',
                      dest='quiet',
                      help=('Suppress the verbose output generated by the '
                            'containers.')),
        CommandOption(CommandOption.TYPE_CHOICE, '--rm',
                      action='store',
                      dest='rm',
                      help=('Remove intermediate containers after a '
                            'successful build.'),
                      default='true',
                      choices=['true', 'false']),
        CommandOption(CommandOption.TYPE_BOOLEAN, '--no-cache',
                      action='store_true',
                      dest='nocache',
                      help='Do not use cache when building the image.'),
        CommandOption(CommandOption.TYPE_DIRPATH, 'path',
                      help='Path or URL where the Dockerfile is located.'),
    ],
    'clear': [],
    'exec': [
        CommandOption(CommandOption.TYPE_BOOLEAN, '-d', '--detach',
                      action='store_true',
                      dest='detach',
                      help='Detached mode: run command in the background'),
        CommandOption(CommandOption.TYPE_CONTAINER, 'container',
                      action='store',
                      help='Container to run command in.',
                      nargs='*'),
        CommandOption(CommandOption.TYPE_COMMAND, 'command',
                      action='store',
                      help='Command to run.'),
    ],
    'info': [
    ],
    'inspect': [
        CommandOption(CommandOption.TYPE_IMAGE, 'image',
                      action='store',
                      dest="image_id",
                      help='Image to inspect.',
                      nargs='*'),
        CommandOption(CommandOption.TYPE_CONTAINER, 'container',
                      action='store',
                      help='Container to inspect.',
                      nargs='*'),
    ],
    'logs': [
        CommandOption(CommandOption.TYPE_BOOLEAN, '-f', '--follow',
                      action='store_true',
                      dest='stream',
                      help='Follow log output.'),
        CommandOption(CommandOption.TYPE_CONTAINER, 'container',
                      action='store',
                      help='Container to retrieve the logs from.'),
    ],
    'pause': [
        CommandOption(CommandOption.TYPE_CONTAINER_RUN, None, 'container',
                      action='store',
                      help='Container ID or name to use.'),
    ],
    'port': [
        CommandOption(CommandOption.TYPE_CONTAINER, None, 'container',
                      action='store',
                      help='Container ID or name to use.'),
    ],
    'ps': [
        CommandOption(CommandOption.TYPE_BOOLEAN, '-a', '--all',
                      action='store_true',
                      dest='all',
                      help='Show all containers. '
                           'Only running containers are shown by default.'),
        CommandOption(CommandOption.TYPE_CONTAINER, None, '--before',
                      action='store',
                      dest='before',
                      help='Show only container created before Id or Name, ' +
                           'include non-running ones.'),
        CommandOption(CommandOption.TYPE_BOOLEAN, '-l', '--latest',
                      action='store_true',
                      dest='latest',
                      help='Show only the latest created container, ' +
                           'include non-running ones.'),
        CommandOption(CommandOption.TYPE_NUMERIC, '-n', None,
                      action='store',
                      dest='limit',
                      help='Show n last created containers, include ' +
                           'non-running ones.'),
        CommandOption(CommandOption.TYPE_BOOLEAN, None, '--no-trunc',
                      action='store_false',
                      dest='trunc',
                      help='Don\'t truncate output.'),
        CommandOption(CommandOption.TYPE_BOOLEAN, '-q', '--quiet',
                      action='store_true',
                      dest='quiet',
                      help='Only display numeric IDs.'),
        CommandOption(CommandOption.TYPE_BOOLEAN, '-s', '--size',
                      action='store_true',
                      dest='latest',
                      help='Display total file sizes.'),
        CommandOption(CommandOption.TYPE_CONTAINER, None, '--since',
                      action='store',
                      dest='since',
                      help='Show only containers created since Id or Name, ' +
                           'include non-running ones.')
    ],
    'pull': [
        CommandOption(CommandOption.TYPE_IMAGE, 'image',
                      action='store',
                      help='Image name to pull.'),
    ],
    'images': [
        CommandOption(CommandOption.TYPE_BOOLEAN, '-a', '--all',
                      action='store_true',
                      dest='all',
                      help='Show all images (by default filter out the ' +
                           'intermediate image layers).'),
        CommandOption(CommandOption.TYPE_IMAGE, '-f', '--filter',
                      action='store',
                      dest='name',
                      help='Provide name to filter on.'),
        CommandOption(CommandOption.TYPE_BOOLEAN, '-q', '--quiet',
                      action='store_true',
                      dest='quiet',
                      help='Only show numeric IDs.')
    ],
    'run': [
        CommandOption(CommandOption.TYPE_BOOLEAN, '-d', '--detach',
                      action='store_true',
                      dest='detach',
                      help=('Detached mode: run the container in the '
                            'background and print the new container ID')),
        CommandOption(CommandOption.TYPE_KEYVALUE, '-e', '--env',
                      action='append',
                      dest='environment',
                      help='Set environment variables.',
                      nargs='*'),
        CommandOption(CommandOption.TYPE_CONTAINER, '--name',
                      action='store',
                      dest='name',
                      help='Assign a name to the container.'),
        CommandOption(CommandOption.TYPE_CONTAINER, '--link',
                      action='append',
                      dest='links',
                      help=('Add link to another container in the form of '
                            '<name|id>:alias. To add multiple links: --link '
                            'name1:alias1 --link name2:alias2...'),
                      nargs='*',
                      api_match=False),
        CommandOption(CommandOption.TYPE_BOOLEAN, '-P', '--publish-all',
                      action='store_true',
                      dest='publish_all_ports',
                      help=('Publish all exposed ports to the host '
                            'interfaces.'),
                      api_match=False),
        CommandOption(CommandOption.TYPE_PORT_BINDING, '-p', '--publish',
                      action='append',
                      dest='port_bindings',
                      help=('Publish a container\'s port to the host. '
                            'Format: ip:hostPort:containerPort or '
                            'ip::containerPort or hostPort:containerPort or '
                            'containerPort. To add multiple ports: --publish '
                            '1111:2222 --publish 3333:4444...'),
                      nargs='*',
                      api_match=False),
        CommandOption(CommandOption.TYPE_BOOLEAN, '-t', '--tty',
                      action='store_true',
                      dest='tty',
                      help='Allocate a pseudo-TTY.'),
        CommandOption(CommandOption.TYPE_IMAGE, 'image',
                      action='store',
                      help='Image ID or name to use.'),
        CommandOption(CommandOption.TYPE_COMMAND, 'command',
                      action='store',
                      help='Command to run in a container.',
                      nargs='*'),
        CommandOption(CommandOption.TYPE_BOOLEAN, '--rm',
                      action='store_true',
                      dest='remove',
                      help=('Remove the container when it exits. '
                            'Can\'t be used with --detach'),
                      api_match=False),
        CommandOption(CommandOption.TYPE_FILEPATH, '-v', '--volume',
                      action='append',
                      dest='volumes',
                      help=('Bind mount a volume (e.g., from the host: -v '
                            '/host-path:/container-path, from Docker: '
                            '-v /container-path).'),
                      nargs='*'),
        CommandOption(CommandOption.TYPE_CONTAINER, '--volumes-from',
                      action='append',
                      dest='volumes_from',
                      help=('Mount volumes from the specified containers. Can '
                            'be specified multiple times. Alternatively, can '
                            'accept a comma-separated string of container '
                            'names.'),
                      nargs='*',
                      api_match=False),
    ],
    'shell': [
        CommandOption(CommandOption.TYPE_CONTAINER_RUN, 'container',
                      action='store',
                      help='Container ID or name to use.'),
        CommandOption(CommandOption.TYPE_CHOICE, 'command',
                      action='store',
                      help='Shell command to execute.',
                      choices=[
                          'bash',
                          'sh',
                          'zsh',
                          '/usr/bin/bash',
                          '/usr/bin/sh',
                          '/usr/bin/zsh',
                          '/usr/local/bin/bash',
                          '/usr/local/bin/sh',
                          '/usr/local/bin/zsh',
                      ],
                      default='bash',
                      nargs='?'),
    ],
    'start': [
        CommandOption(CommandOption.TYPE_BOOLEAN, '-a', '--attach',
                      action='store_true',
                      dest='attach',
                      help='Attach container\'s STDOUT and STDERR and ' +
                           'forward all signals to the process.',
                      api_match=False),
        CommandOption(CommandOption.TYPE_CONTAINER, 'container',
                      action='store',
                      help='Container ID or name to use.'),
    ],
    'rm': [
        CommandOption(CommandOption.TYPE_CONTAINER, 'container',
                      action='store',
                      help='Container ID or name to use.',
                      nargs='+'),
        CommandOption(CommandOption.TYPE_BOOLEAN, '--all-stopped',
                      action='store_true',
                      dest='all_stopped',
                      help='Shortcut to remove all stopped containers.'),
    ],
    'rmi': [
        CommandOption(CommandOption.TYPE_IMAGE_TAG, 'image',
                      action='store',
                      help='Image name name to remove.',
                      nargs='+'),
        CommandOption(CommandOption.TYPE_BOOLEAN, '--all-dangling',
                      action='store_true',
                      dest='all_dangling',
                      help='Shortcut to remove all dangling images.'),
    ],
    'search': [
        CommandOption(CommandOption.TYPE_IMAGE, 'term',
                      action='store',
                      help='A term to search for.'),
    ],
    'stop': [
        CommandOption(CommandOption.TYPE_CONTAINER_RUN, 'container',
                      action='store',
                      help='Container ID or name to use.'),
    ],
    'top': [
        CommandOption(CommandOption.TYPE_CONTAINER_RUN, 'container',
                      action='store',
                      help='Container ID or name to use.'),
    ],
    'unpause': [
        CommandOption(CommandOption.TYPE_CONTAINER_RUN, None, 'container',
                      action='store',
                      help='Container ID or name to use.'),
    ]
}


HIDDEN_OPTIONS = {
    'start': [
        CommandOption(CommandOption.TYPE_BOOLEAN, '-P', '--publish-all',
                      action='store_true',
                      dest='publish_all_ports',
                      help=('Publish all exposed ports to the host '
                            'interfaces.')),
        CommandOption(CommandOption.TYPE_PORT_BINDING, '-p', '--publish',
                      action='append',
                      dest='port_bindings',
                      help=('Publish a container\'s port to the host. '
                            'Format: ip:hostPort:containerPort or '
                            'ip::containerPort or hostPort:containerPort or '
                            'containerPort'),
                      nargs='*'),
    ],
    'run': [
        CommandOption(CommandOption.TYPE_NUMERIC, 'ports', None,
                      action='append',
                      dest='ports',
                      nargs='*'),
        CommandOption(CommandOption.TYPE_OBJECT, 'host_config', None,
                      action='store',
                      dest='host_config'),
    ],
}


def all_option_names():
    """
    Helper method to go through all commands and return all option names,
    long or short.
    :return: iterable
    """
    opts = {OPTION_HELP.short_name, OPTION_HELP.long_name}
    for command in COMMAND_OPTIONS:
        for opt in COMMAND_OPTIONS[command]:
            if opt.short_name and opt.short_name.startswith('-'):
                opts.add(opt.short_name)
            if opt.long_name and opt.long_name.startswith('--'):
                opts.add(opt.long_name)
    return sorted(list(opts))


def find_option(command, name):
    """
    Helper method to find command option by its name.
    :param command: string
    :param name: string
    :return: CommandOption
    """
    # TODO: use all_options
    if command in COMMAND_OPTIONS:
        if name == 'help':
            return OPTION_HELP
        for opt in COMMAND_OPTIONS[command]:
            if name in [opt.short_name, opt.long_name]:
                return opt
    return None


def allowed_args(cmd, **kwargs):
    """
    Return only arguments that the command accepts.
    :param cmd: string
    :param kwargs: dict
    :return: dict
    """
    matches = {}
    available = all_supported(cmd)
    if available:
        for k in kwargs:
            if k in available:
                matches[k] = kwargs[k]
    return matches


def all_options(command, include_hidden=False):
    """
    Helper method to find all command options.
    :param command: string
    :param include_hidden: boolean
    :return: set of CommandOption
    """
    result = [OPTION_HELP]
    if command in COMMAND_OPTIONS:
        result.extend(COMMAND_OPTIONS[command])
    if include_hidden and command in HIDDEN_OPTIONS:
        result.extend(HIDDEN_OPTIONS[command])
    return result


def all_supported(command):
    """
    Helper method to find all command options that docker-py supports.
    :param command: string
    :return: set of CommandOption
    """
    result = {OPTION_HELP}

    if command in COMMAND_OPTIONS:
        result.update(
            [x.dest for x in COMMAND_OPTIONS[command] if x.api_match])

    if command in HIDDEN_OPTIONS:
        result.update([x.dest for x in HIDDEN_OPTIONS[command]])

    return result


def parse_command_options(cmd, params):
    """
    Parse options for a given command.
    :param cmd: string: command name
    :param params: list: all tokens after command name
    :return: parser, args, opts
    """
    parser = OptParser(prog=cmd, add_help_option=False)
    parser.disable_interspersed_args()
    for opt in all_options(cmd, include_hidden=True):
        if opt.name.startswith('-'):
            parser.add_option(*opt.args, **opt.kwargs)
    popts, pargs = parser.parse_args(params)
    parser.assert_option_format()
    popts = vars(popts)
    return parser, popts, pargs


def format_command_help(cmd):
    """
    Format help string for the command.
    :param cmd: string: command name
    :return: string
    """
    usage = [cmd, '[options]']
    alls = all_options(cmd)

    for opt in alls:
        if not opt.name.startswith('-'):
            optname = "[{0}]".format(opt.name) if opt.is_optional else opt.name
            usage.append(optname)

    usage = ' '.join(usage)

    parser = OptParser(prog=cmd, add_help_option=False, usage=usage)

    for opt in alls:
        if opt.name.startswith('-'):
            parser.add_option(*opt.args, **opt.kwargs)

    return parser.format_help()


class OptParser(OptionParser):

    # TODO: Bad bad bad. There should be a better way to do this.
    def assert_option_format(self):
        """
        I don't want environment vars to be provided as
        "-e KEY VALUE", I want "-e KEY=VALUE" instead.
        Would argparse help here?
        """
        dict_values = vars(self.values)
        if 'environment' in dict_values and dict_values['environment']:
            for envar in dict_values['environment']:
                if '=' not in envar:
                    raise OptionError(
                        'Usage: -e KEY1=VALUE1 -e KEY2=VALUE2...',
                        '-e')

    """
    Wrapper around OptionParser.
    Overrides error method to throw an exception.
    """
    def error(self, msg):
        """error(msg : string)

        Print a usage message incorporating 'msg' to stderr and exit.
        If you override this in a subclass, it should not return -- it
        should either exit or raise an exception.
        """
        raise Exception("Error parsing options: {0}".format(msg))
